### ISSUE TITLE
Bump QuickCheck upper boundary constraint

### ISSUE THREAD

**Issue by AlexeyRaga** [Fuuzetsu/aeson-schema#14]
Is it possible to bump QuickCheck upper boundary constraint to at least 2.13?
It can't be solved with `Servant` otherwise because it requires `QuickCheck >= >=2.12.6.1`

A revision on Hackage would do too, no need for a full new version release.

Thanks!

**Comment by Fuuzetsu** [comment]
Hopefully this works for you: https://hackage.haskell.org/package/aeson-schema-0.4.2.0
