### ISSUE TITLE
[RFC] Native replacement for regex-pcre  ?

### ISSUE THREAD

**Issue by ocramz** [Fuuzetsu/aeson-schema#16]
I just ran into a build failure on a machine that doesn't have pkg-config (2020 Mac M1)

Are there native Haskell replacements for regular expressions we could use here instead?

**Comment by Fuuzetsu** [comment]
regex-dfa/regex-tdfa are native AFAIU; not sure if they are a simple drop-in

**Comment by ocramz** [comment]
Closed by #21
