### ISSUE TITLE
Upgrade to latest aeson et. all

### ISSUE THREAD

**Issue by bcherny** [Fuuzetsu/aeson-schema#7]
Hi! This library looks perfect for what I need, but when I try to install it it looks like many of this lib's dependencies are out of date:

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for aeson-schema-0.4.1.1:
    QuickCheck-2.9.2 must match >=2.4.2 && <2.9 (latest applicable is 2.8.2)
    aeson-1.1.2.0 must match >=0.11.0.0 && <0.12 (latest applicable is 0.11.3.0)
    syb-0.7 must match >=0.4.4 && <0.7 (latest applicable is 0.6)
    template-haskell-2.11.1.0 must match <2.11 (latest applicable is 2.10.0.0)
    vector-0.12.0.1 must match >=0.10 && <0.12 (latest applicable is 0.11.0.0)
```

Is it possible to update the dependencies, or is there a workaround you suggest?

Thanks!

**Comment by Fuuzetsu** [comment]
There's no reason why dependencies could not be updated but my spare time is pretty low. Fastest way is to send a PR which I'd be happy to accept or hope I remember this when I find some time (maybe even tonight!).

**Comment by christian-marie** [comment]
I think this is superceded by the latest PR merged. Still need to make a release but have been dealing with local stack issues.

**Comment by christian-marie** [comment]
#11

**Comment by christian-marie** [comment]
Oh, sorry, missed this completely. Yes we should update to the latest aeson. I'll try to take a look at some point.

**Comment by christian-marie** [comment]
I thought this might have been done, but it was not. Disreguard churn, apologies.

**Comment by christian-marie** [comment]
This is likely already done by now. If you still can't build, please reopen.
